// Auth action types
export const AUTH_START = 'AUTH_START';
export const AUTH_USER_LOGIN_SUCCESS = 'AUTH_USER_LOGIN_SUCCESS';
export const AUTH_RESTAURANT_LOGIN_SUCCESS = 'AUTH_RESTAURANT_LOGIN_SUCCESS';
export const AUTH_AUTO_RENEW_SUCCESS = 'AUTH_AUTO_RENEW_SUCCESS';
export const AUTH_PHOTO_SUCCESS = 'AUTH_PHOTO_SUCCESS';
export const AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS';
export const AUTH_DATA_UPDATE_SUCCESS = 'AUTH_DATA_UPDATE_SUCCESS';
export const CLEAR_SIGNUP = 'CLEAR_SIGNUP';
export const AUTH_ADMIN_LOGIN_SUCCESS = 'AUTH_ADMIN_LOGIN_SUCCESS';
export const AUTH_ADMIN_VERIFY_SUCCESS = 'AUTH_ADMIN_VERIFY_SUCCESS';
export const RESEND_CODE_SUCCESS = 'RESEND_CODE_SUCCESS';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_MESSAGE = 'AUTH_MESSAGE';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
export const SET_HASH = 'SET_HASH';


// Content
export const CONTENT_START = 'CONTENT_START';
export const CONTENT_SUCCESS = 'CONTENT_SUCCESS';
export const CONTENT_FAIL = 'CONTENT_FAIL';


// Frontend
export const MEALS_RESET = 'MEALS_RESET';
export const MEALS_START = 'MEALS_START';
export const MEALS_SUCCESS = 'MEALS_SUCCESS';
export const MEALS_FAIL = 'MEALS_FAIL';


// Backend
export const ADMINS_RESET = 'ADMINS_RESET';
export const ADMINS_START = 'ADMINS_START';
export const ADMINS_SUCCESS = 'ADMINS_SUCCESS';
export const ADMINS_FAIL = 'ADMINS_FAIL';

export const CMS_RESET = 'CMS_RESET';
export const CMS_START = 'CMS_START';
export const CMS_SUCCESS = 'CMS_SUCCESS';
export const CMS_FAIL = 'CMS_FAIL';

export const NOTIFICATIONS_RESET = 'NOTIFICATIONS_RESET';
export const NOTIFICATIONS_START = 'NOTIFICATIONS_START';
export const NOTIFICATIONS_SUCCESS = 'NOTIFICATIONS_SUCCESS';
export const NOTIFICATIONS_FAIL = 'NOTIFICATIONS_FAIL';

export const DASHBOARD_RESET = 'DASHBOARD_RESET';
export const DASHBOARD_START = 'DASHBOARD_START';
export const DASHBOARD_SUCCESS = 'DASHBOARD_SUCCESS';
export const DASHBOARD_FAIL = 'DASHBOARD_FAIL';

export const FEATURES_RESET = 'FEATURES_RESET';
export const FEATURES_START = 'FEATURES_START';
export const FEATURES_SUCCESS = 'FEATURES_SUCCESS';
export const FEATURES_FAIL = 'FEATURES_FAIL';

export const LANGUAGES_RESET = 'LANGUAGES_RESET';
export const LANGUAGES_START = 'LANGUAGES_START';
export const LANGUAGES_SUCCESS = 'LANGUAGES_SUCCESS';
export const LANGUAGES_FAIL = 'LANGUAGES_FAIL';

export const ROLES_RESET = 'ROLES_RESET';
export const ROLES_START = 'ROLES_START';
export const ROLES_SUCCESS = 'ROLES_SUCCESS';
export const ROLES_FAIL = 'ROLES_FAIL';

export const USERS_RESET = 'USERS_RESET';
export const USERS_START = 'USERS_START';
export const USERS_SUCCESS = 'USERS_SUCCESS';
export const USERS_FAIL = 'USERS_FAIL';

export const METHODS_RESET = 'METHODS_RESET';
export const METHODS_START = 'METHODS_START';
export const METHODS_SUCCESS = 'METHODS_SUCCESS';
export const METHODS_FAIL = 'METHODS_FAIL';



export const RESTAURANTS_RESET = 'RESTAURANTS_RESET';
export const RESTAURANTS_START = 'RESTAURANTS_START';
export const RESTAURANTS_SUCCESS = 'RESTAURANTS_SUCCESS';
export const RESTAURANTS_FAIL = 'RESTAURANTS_FAIL';

export const CATEGORIES_RESET = 'CATEGORIES_RESET';
export const CATEGORIES_START = 'CATEGORIES_START';
export const CATEGORIES_SUCCESS = 'CATEGORIES_SUCCESS';
export const CATEGORIES_FAIL = 'CATEGORIES_FAIL';

export const ADDONS_RESET = 'ADDONS_RESET';
export const ADDONS_START = 'ADDONS_START';
export const ADDONS_SUCCESS = 'ADDONS_SUCCESS';
export const ADDONS_FAIL = 'ADDONS_FAIL';

export const COMMENTS_RESET = 'COMMENTS_RESET';
export const COMMENTS_START = 'COMMENTS_START';
export const COMMENTS_SUCCESS = 'COMMENTS_SUCCESS';
export const COMMENTS_FAIL = 'COMMENTS_FAIL';

export const PLANS_RESET = 'PLANS_RESET';
export const PLANS_START = 'PLANS_START';
export const PLANS_SUCCESS = 'PLANS_SUCCESS';
export const PLANS_FAIL = 'PLANS_FAIL';

export const RECHARGES_RESET = 'RECHARGES_RESET';
export const RECHARGES_START = 'RECHARGES_START';
export const RECHARGES_SUCCESS = 'RECHARGES_SUCCESS';
export const RECHARGES_FAIL = 'RECHARGES_FAIL';

export const SETTINGS_RESET = 'SETTINGS_RESET';
export const SETTINGS_START = 'SETTINGS_START';
export const SETTINGS_SUCCESS = 'SETTINGS_SUCCESS';
export const SETTINGS_FAIL = 'SETTINGS_FAIL';

