// Auth action types
export const AUTH_START = 'AUTH_START';
export const AUTH_USER_LOGIN_SUCCESS = 'AUTH_USER_LOGIN_SUCCESS';
export const AUTH_ADMIN_LOGIN_SUCCESS = 'AUTH_ADMIN_LOGIN_SUCCESS';
export const AUTH_ADMIN_VERIFY_SUCCESS = 'AUTH_ADMIN_VERIFY_SUCCESS';
export const RESEND_CODE_SUCCESS = 'RESEND_CODE_SUCCESS';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_MESSAGE = 'AUTH_MESSAGE';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
export const SET_HASH = 'SET_HASH';


// Content
export const CONTENT_START = 'CONTENT_START';
export const CONTENT_SUCCESS = 'CONTENT_SUCCESS';
export const CONTENT_FAIL = 'CONTENT_FAIL';


// Frontend
export const MEALS_RESET = 'MEALS_RESET';
export const MEALS_START = 'MEALS_START';
export const MEALS_SUCCESS = 'MEALS_SUCCESS';
export const MEALS_FAIL = 'MEALS_FAIL';


// Backend
export const ADMINS_RESET = 'ADMINS_RESET';
export const ADMINS_START = 'ADMINS_START';
export const ADMINS_SUCCESS = 'ADMINS_SUCCESS';
export const ADMINS_FAIL = 'ADMINS_FAIL';

export const CMS_RESET = 'CMS_RESET';
export const CMS_START = 'CMS_START';
export const CMS_SUCCESS = 'CMS_SUCCESS';
export const CMS_FAIL = 'CMS_FAIL';

export const DASHBOARD_RESET = 'DASHBOARD_RESET';
export const DASHBOARD_START = 'DASHBOARD_START';
export const DASHBOARD_SUCCESS = 'DASHBOARD_SUCCESS';
export const DASHBOARD_FAIL = 'DASHBOARD_FAIL';

export const FEATURES_RESET = 'FEATURES_RESET';
export const FEATURES_START = 'FEATURES_START';
export const FEATURES_SUCCESS = 'FEATURES_SUCCESS';
export const FEATURES_FAIL = 'FEATURES_FAIL';

export const ISSUES_RESET = 'ISSUES_RESET';
export const ISSUES_START = 'ISSUES_START';
export const ISSUES_SUCCESS = 'ISSUES_SUCCESS';
export const ISSUES_FAIL = 'ISSUES_FAIL';

export const LANGUAGES_RESET = 'LANGUAGES_RESET';
export const LANGUAGES_START = 'LANGUAGES_START';
export const LANGUAGES_SUCCESS = 'LANGUAGES_SUCCESS';
export const LANGUAGES_FAIL = 'LANGUAGES_FAIL';

export const PLATFORMS_RESET = 'PLATFORMS_RESET';
export const PLATFORMS_START = 'PLATFORMS_START';
export const PLATFORMS_SUCCESS = 'PLATFORMS_SUCCESS';
export const PLATFORMS_FAIL = 'PLATFORMS_FAIL';

export const ROLES_RESET = 'ROLES_RESET';
export const ROLES_START = 'ROLES_START';
export const ROLES_SUCCESS = 'ROLES_SUCCESS';
export const ROLES_FAIL = 'ROLES_FAIL';

export const USERS_RESET = 'USERS_RESET';
export const USERS_START = 'USERS_START';
export const USERS_SUCCESS = 'USERS_SUCCESS';
export const USERS_FAIL = 'USERS_FAIL';



export const CYCLES_RESET = 'CYCLES_RESET';
export const CYCLES_START = 'CYCLES_START';
export const CYCLES_SUCCESS = 'CYCLES_SUCCESS';
export const CYCLES_FAIL = 'CYCLES_FAIL';

export const LEVELS_RESET = 'LEVELS_RESET';
export const LEVELS_START = 'LEVELS_START';
export const LEVELS_SUCCESS = 'LEVELS_SUCCESS';
export const LEVELS_FAIL = 'LEVELS_FAIL';

export const CLASSROOMS_RESET = 'CLASSROOMS_RESET';
export const CLASSROOMS_START = 'CLASSROOMS_START';
export const CLASSROOMS_SUCCESS = 'CLASSROOMS_SUCCESS';
export const CLASSROOMS_FAIL = 'CLASSROOMS_FAIL';

export const YEARS_RESET = 'YEARS_RESET';
export const YEARS_START = 'YEARS_START';
export const YEARS_SUCCESS = 'YEARS_SUCCESS';
export const YEARS_FAIL = 'YEARS_FAIL';

export const STUDENTS_RESET = 'STUDENTS_RESET';
export const STUDENTS_START = 'STUDENTS_START';
export const STUDENTS_SUCCESS = 'STUDENTS_SUCCESS';
export const STUDENTS_FAIL = 'STUDENTS_FAIL';

export const SUBJECTS_RESET = 'SUBJECTS_RESET';
export const SUBJECTS_START = 'SUBJECTS_START';
export const SUBJECTS_SUCCESS = 'SUBJECTS_SUCCESS';
export const SUBJECTS_FAIL = 'SUBJECTS_FAIL';

export const SESSIONS_RESET = 'SESSIONS_RESET';
export const SESSIONS_START = 'SESSIONS_START';
export const SESSIONS_SUCCESS = 'SESSIONS_SUCCESS';
export const SESSIONS_FAIL = 'SESSIONS_FAIL';

export const TRIMESTERS_RESET = 'TRIMESTERS_RESET';
export const TRIMESTERS_START = 'TRIMESTERS_START';
export const TRIMESTERS_SUCCESS = 'TRIMESTERS_SUCCESS';
export const TRIMESTERS_FAIL = 'TRIMESTERS_FAIL';

export const SEQUENCES_RESET = 'SEQUENCES_RESET';
export const SEQUENCES_START = 'SEQUENCES_START';
export const SEQUENCES_SUCCESS = 'SEQUENCES_SUCCESS';
export const SEQUENCES_FAIL = 'SEQUENCES_FAIL';

export const EXAM_TYPES_RESET = 'EXAM_TYPES_RESET';
export const EXAM_TYPES_START = 'EXAM_TYPES_START';
export const EXAM_TYPES_SUCCESS = 'EXAM_TYPES_SUCCESS';
export const EXAM_TYPES_FAIL = 'EXAM_TYPES_FAIL';

export const EXAMS_RESET = 'EXAMS_RESET';
export const EXAMS_START = 'EXAMS_START';
export const EXAMS_SUCCESS = 'EXAMS_SUCCESS';
export const EXAMS_FAIL = 'EXAMS_FAIL';

export const MARKS_RESET = 'MARKS_RESET';
export const MARKS_START = 'MARKS_START';
export const MARKS_SUCCESS = 'MARKS_SUCCESS';
export const MARKS_FAIL = 'MARKS_FAIL';