export {
    authUserLogin,
    authAdminLogin,
    authAdminVerify,
    resendCode,
    authLogout,
    setAuthRedirectPath,
    setHash,
    authCheckState,
} from './auth';

export {
    getContent,
    setLanguage,
} from './content';

export {
    resetAdmins,
    getAdmins,
    getAdmin,
    postAdmins,
    patchAdmins,
    deleteAdmins,

    resetCms,
    getCms,
    postCms,
    patchCms,
    deleteCms,

    resetDashboard,
    getDashboard,

    resetFeatures,
    getFeatures,
    getFeature,
    postFeatures,
    patchFeatures,
    deleteFeatures,



    resetLanguages,
    getLanguages,
    getLanguage,
    postLanguages,
    patchLanguages,
    deleteLanguages,

    resetRoles,
    getRoles,
    getRole,
    getRolesInfo,
    postRoles,
    patchRoles,
    deleteRoles,

    resetUsers,
    getUsers,
    getUser,
    getUsersInfo,
    postUsers,
    patchUsers,
    deleteUsers,



    resetClassrooms,
    getClassrooms,
    getClassroom,
    getClassroomsInfo,
    postClassrooms,
    patchClassrooms,
    deleteClassrooms,

    resetCycles,
    getCycles,
    getCycle,
    postCycles,
    patchCycles,
    deleteCycles,
    
    resetExams,
    getExams,
    getExamsInfo,
    getExam,
    postExams,
    patchExams,
    deleteExams,
    
    resetExamTypes,
    getExamTypes,
    getExamType,
    postExamTypes,
    patchExamTypes,
    deleteExamTypes,
    
    resetLevels,
    getLevels,
    getLevelsInfo,
    getLevel,
    postLevels,
    patchLevels,
    deleteLevels,
    
    resetMarks,
    getMarks,
    getMarksInfo,
    getMark,
    postMarks,
    patchMarks,
    deleteMarks,
    
    resetSequences,
    getSequences,
    getSequencesInfo,
    getSequence,
    postSequences,
    patchSequences,
    deleteSequences,
    
    resetSessions,
    getSessions,
    getSessionsInfo,
    getSession,
    postSessions,
    patchSessions,
    deleteSessions,
    
    resetStudents,
    getStudents,
    getStudent,
    postStudents,
    patchStudents,
    deleteStudents,
    
    resetSubjects,
    getSubjects,
    getSubject,
    postSubjects,
    patchSubjects,
    deleteSubjects,
    
    resetTrimesters,
    getTrimesters,
    getTrimestersInfo,
    getTrimester,
    postTrimesters,
    patchTrimesters,
    deleteTrimesters,
    
    resetYears,
    getYears,
    getYear,
    postYears,
    patchYears,
    deleteYears,
} from './backend';